# -*- coding: utf-8 -*-
"""Assignment#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arzuZBWsP-1v0pZpujawqKpHnHHT81Ed

**Assignment # 1**

**1. Write a Python program to print the following string in a specific format
(see the output).
 Twinkle, twinkle, little star,
         How I wonder what you are!
                 Up above the world so high,
                 Like a diamond in the sky.
 Twinkle, twinkle, little star,
         How I wonder what you are!**
"""

print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\t\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")

"""**2. Write a Python program to get the Python version you are using**"""

import sys
print("Python version that im using !!!")
print (sys.version)
print("Version info.")
print (sys.version_info)

"""**3. Write a Python program to display the current date and time.**"""

import datetime
a = datetime.datetime.now()

print ("Current date and time in am ,pm format : ")
print (a.strftime("%d-%m-%Y %I:%M:%S %p"))

print ("Current date and time 24 hour format : ")
print (a.strftime("%Y-%m-%d %H:%M:%S"))

"""**4. Write a Python program which accepts the radius of a circle from the user
and compute the area.**
"""

pi=3.14
radius =float (input ('Enter the radius of a circle'))
area=pi*radius*radius
print("Area of the circle is : %.2f"  %area)

"""**5. Write a Python program which accepts the user's first and last name and
print them in reverse order with a space between them.**
"""

first_name = input("Enter your First Name : ")
last_name = input("Enter your Last Name : ")
print (last_name + " " + first_name)

"""**6. Write a python program which takes two inputs from user and print them
additiont**
"""

a = int(input("Enter first number for addition :"))
b = int(input("Enter second number for addition :"))
print("Numbers after addition :", a+b)

